// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	Name     *string  `json:"name,omitempty"`
	LastName *string  `json:"lastName,omitempty"`
	Gender   *float64 `json:"gender,omitempty"`
	Email    *string  `json:"email,omitempty"`
	Password *string  `json:"password,omitempty"`
}

type User struct {
	Name     string  `json:"name"`
	LastName string  `json:"lastName"`
	Gender   float64 `json:"gender"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
}
